name: First Action
on: workflow_dispatch
jobs:
  first-jon:
    runs-on:  ubuntu-latest
    steps:
      - name: Print hello
        run: |
              echo "hello world!!"
              echo "mutli line"
      - name: Print Bye
        run: echo "good-bye"
